### ISSUE TITLE
1.2 /meta_knowledge_graph validation failure

### ISSUE THREAD

**Issue by cbizon** [suihuanglab/spoke-kp#3]
Hi Brett - I am running into some problems getting aragorn 1.2 to talk to spoke 1.2.  There are some validation errors in the /meta_knowledge_graph endpoint.  I think that the main one is that the value of "original_attribute_names" has to be a list (https://github.com/NCATSTranslator/ReasonerAPI/blob/master/docs/reference.md#metaattribute-) but the ones in spoke are (sometimes?) a string:
```
"attributes": [
        {
          "attribute_type_id": "biolink:description",
          "constraint_use": false,
          "original_attribute_names": "description"
        }
]
```

**Comment by brettasmi** [comment]
Thanks @cbizon, I'll try to make this change and deploy it today.

**Comment by brettasmi** [comment]
Should be fixed now @cbizon 

e.g. from: https://spokekp.healthdatascience.cloud/api/v1.2/meta_knowledge_graph
```
    "biolink:CellularComponent": {
      "attributes": [
        {
          "attribute_type_id": "biolink:description",
          "constraint_use": false,
          "original_attribute_names": [
            "description"
          ]
        }, ...
      ], ...
    }
```

Is it problematic if you receive an array of `attributes` with multiple entries of the same `attribute_type_id`? For example:

```
    "biolink:CellularComponent": {
      "attributes": [
        {
          "attribute_type_id": "biolink:description",
          "constraint_use": false,
          "original_attribute_names": [
            "description"
          ]
        },
        {
          "attribute_type_id": "biolink:description",
          "constraint_use": false,
          "original_attribute_names": [
            "description-number-2"
          ]
        }, ...
      ], ...
    }
```

I've implemented this quickly, so you might receive something like the above. I assume the spirit of making the `original_attribute_names` an array was so that the above could be collapsed into a single `attributes` entry, but I couldn't verify that in my inspection of the TRAPI spec, the implementation rules, or the PR that added MetaAttributes.

**Comment by cbizon** [comment]
I think that you're correct about the intent, but I think that your second snippet would also be legal.  I could imagine it causing problems for somebody, but it should be ok for us.

Thanks for the quick resolution, ARAGORN is now talking to SPOKE again!
